# Generated by Django 4.2.13 on 2024-06-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0002_kitchenlatetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenlunch',
            name='location',
            field=models.CharField(choices=[('JP23', 'JP23'), ('KP5', 'KP5'), ('TS17', 'TS17')], default='JP23', max_length=50),
        ),
    ]
