# Generated by Django 4.2.13 on 2024-06-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0004_apartmentcleaning_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentcleaning',
            options={'verbose_name': 'Apartment Cleaning', 'verbose_name_plural': 'Apartment Cleaning'},
        ),
        migrations.AlterModelOptions(
            name='drystoragecleaning',
            options={'verbose_name': 'Dry Storage Cleaning', 'verbose_name_plural': 'Dry Storage Cleaning'},
        ),
        migrations.AlterModelOptions(
            name='kitchenlate',
            options={'verbose_name': 'Kitchen Department Late Shift', 'verbose_name_plural': 'Kitchen Department Late Shift'},
        ),
        migrations.AlterModelOptions(
            name='kitchenlatetask',
            options={'verbose_name': 'Kitchen Department Late Shift(Task)', 'verbose_name_plural': 'Kitchen Department Late Shift(Task)'},
        ),
        migrations.AlterModelOptions(
            name='kitchenlunchtask',
            options={'verbose_name': 'Kitchen Department Lunch Shift(Task)', 'verbose_name_plural': 'Kitchen Department Lunch Shift(Task)'},
        ),
        migrations.AlterModelOptions(
            name='kitchenspecialcleaningmonday',
            options={'verbose_name': 'Kitchen Department Specialcleaning(Monday)', 'verbose_name_plural': 'Kitchen Department Specialcleaning(Monday)'},
        ),
        migrations.AlterModelOptions(
            name='terminallate',
            options={'verbose_name': 'Terminal Department Late Shift', 'verbose_name_plural': 'Terminal Department Late Shift'},
        ),
        migrations.AlterModelOptions(
            name='terminallunch',
            options={'verbose_name': 'Terminal Department Lunch Shift', 'verbose_name_plural': 'Terminal Department Lunch Shift'},
        ),
        migrations.AlterModelOptions(
            name='wednesdaycleaning',
            options={'verbose_name': 'Kitchen Special Cleaning(Wednesday)', 'verbose_name_plural': 'Kitchen Special Cleaning(Wednesday)'},
        ),
    ]
