# Generated by Django 4.2.13 on 2024-06-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0005_alter_apartmentcleaning_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentcleaning',
            options={'verbose_name': 'Apartment Cleaning(Wednesday)', 'verbose_name_plural': 'Apartment Cleaning(Wednesday)'},
        ),
        migrations.AlterModelOptions(
            name='drystoragecleaning',
            options={'verbose_name': 'Dry Storage Cleaning(Wednesday)', 'verbose_name_plural': 'Dry Storage Cleaning(Wednesday)'},
        ),
        migrations.AlterModelOptions(
            name='kitchenlate',
            options={'verbose_name': 'Kitchen Department Late Shift(Quantity)', 'verbose_name_plural': 'Kitchen Department Late Shift(Quantity)'},
        ),
        migrations.AlterModelOptions(
            name='kitchenlunch',
            options={'verbose_name': 'Kitchen Department Lunch Shift(Quantity)', 'verbose_name_plural': 'Kitchen Department Lunch Shift(Quantity)'},
        ),
    ]
